name: 'Manual Rollback Action'
description: 'Checkout master, back it up, and rollback to the previous commit erasing the current commit history'
author: 'Raiyan Yahya'
branding:
  icon: 'skip-back'
  color: 'red'

inputs:
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
      shell: bash

    - name: Run manual rollback script
      run: |
        chmod +x ${GITHUB_ACTION_PATH}/entrypoint.sh
        ${GITHUB_ACTION_PATH}/entrypoint.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
